import { warriorAbilities } from "../../assets/abilities/warriorAbilities";
import { rogueAbilities } from "../../assets/abilities/rogueAbilities";
import { mageAbilities } from "../../assets/abilities/mageAbilities";

export const CreateWarrior = {
  playerClass: "warrior",
  classImg: "/sprites/select/warrior_select.png",
  name: "Almith",
  level: 1,
  talentPoints: 1,
  talentArr: [
    {
      name: "+5% HP",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/HP_1.png",
    },
    {
      name: "+5% Attack",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/ATK_1.png",
    },
    {
      name: "Special Rate",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/SPECIAL_1.png",
    },
    {
      name: "+10% HP",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/HP_2.png",
    },
    {
      name: "+10% Attack",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/ATK_2.png",
    },
    {
      name: "Special Rate+",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/SPECIAL_2.png",
    },
    {
      name: "+20% HP",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/HP_3.png",
    },
    {
      name: "+20% Attack",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/ATK_3.png",
    },
    {
      name: "Special Rate++",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/SPECIAL_3.png",
    },
  ],
  experience: 0,
  experienceToLevel: undefined,
  maxHP: undefined,
  curHP: undefined,
  armor: undefined,
  spirit: undefined,
  special: 0,
  bossStage: 1,
  attack: undefined,
  spellpower: undefined,
  speed: 5,
  inBattle: false,
  abilities: warriorAbilities,
  spriteSheet: "/sprites/playerClasses/Warrior/Warrior.png",
  basicIcon: "/sprites/playerClasses/Warrior/w_basic.png",
  specialIcon: "/sprites/playerClasses/Warrior/w_special.png",
  spriteWidth: 100,
  spriteHeight: 64,
  sheetWidth: 500,
  sheetHeight: 768,
  frames: {
    idleStart: 1,
    idleEnd: 12,
    attackStart: 23,
    attackEnd: 31,
    hurtStart: 33,
    hurtEnd: 35,
    dieStart: 33,
    dieEnd: 46,
  },
};

export const CreateRogue = {
  playerClass: "rogue",
  classImg: "/sprites/select/rogue_select.png",
  name: "Almith",
  level: 1,
  talentPoints: 1,
  talentArr: [
    {
      name: "+5% HP",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/HP_1.png",
    },
    {
      name: "+5% Speed",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/SPD_1.png",
    },
    {
      name: "Special Rate",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/SPECIAL_1.png",
    },
    {
      name: "+10% HP",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/HP_2.png",
    },
    {
      name: "+10% Speed",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/SPD_2.png",
    },
    {
      name: "Special Rate+",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/SPECIAL_2.png",
    },
    {
      name: "+20% HP",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/HP_3.png",
    },
    {
      name: "+20% Speed",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/SPD_3.png",
    },
    {
      name: "Special Rate++",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/SPECIAL_3.png",
    },
  ],
  experience: 0,
  experienceToLevel: undefined,
  maxHP: undefined,
  curHP: undefined,
  armor: undefined,
  spirit: undefined,
  special: 0,
  bossStage: 1,
  attack: undefined,
  spellpower: undefined,
  speed: 50,
  loaded: true,
  inBattle: false,
  abilities: rogueAbilities,
  spriteSheet: "/sprites/playerClasses/Rogue/Rogue.png",
  basicIcon: "/sprites/playerClasses/Rogue/r_basic.png",
  specialIcon: "/sprites/playerClasses/Rogue/r_special.png",
  spriteWidth: 100,
  spriteHeight: 100,
  sheetWidth: 1000,
  sheetHeight: 1100,
  frames: {
    idleStart: 1,
    idleEnd: 11,
    attackStart: 82,
    attackEnd: 102,
    hurtStart: 36,
    hurtEnd: 39,
    dieStart: 22,
    dieEnd: 35,
  },
};

export const CreateMage = {
  playerClass: "mage",
  classImg: "/sprites/select/mage_select.png",
  name: "Almith",
  level: 1,
  talentPoints: 1,
  talentArr: [
    {
      name: "+5% HP",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/HP_1.png",
    },
    {
      name: "+5% Spellpower",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/MAG_1.png",
    },
    {
      name: "Special Rate",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/SPECIAL_1.png",
    },
    {
      name: "+10% HP",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/HP_2.png",
    },
    {
      name: "+10% Spellpower",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/MAG_2.png",
    },
    {
      name: "Special Rate+",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/SPECIAL_2.png",
    },
    {
      name: "+20% HP",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/HP_3.png",
    },
    {
      name: "+20% Spellpower",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/MAG_3.png",
    },
    {
      name: "Special Rate++",
      points: 0,
      max: 5,
      descrition: "",
      icon: "/talent_icons/SPECIAL_3.png",
    },
  ],
  experience: 0,
  experienceToLevel: undefined,
  maxHP: undefined,
  curHP: undefined,
  armor: undefined,
  spirit: undefined,
  special: 0,
  bossStage: 1,
  attack: undefined,
  spellpower: undefined,
  speed: 50,
  loaded: true,
  inBattle: false,
  abilities: mageAbilities,
  spriteSheet: "/sprites/playerClasses/Mage/Firemage.png",
  basicIcon: "/sprites/playerClasses/Mage/m_basic.png",
  specialIcon: "/sprites/playerClasses/Mage/m_special.png",
  spriteWidth: 100,
  spriteHeight: 100,
  sheetWidth: 800,
  sheetHeight: 900,
  frames: {
    idleStart: 1,
    idleEnd: 10,
    attackStart: 48,
    attackEnd: 65,
    hurtStart: 19,
    hurtEnd: 21,
    dieStart: 19,
    dieEnd: 34,
  },
};
